apiVersion: v1
kind: Pod
metadata:
  name: pod4
  labels:
    app: helloworld
spec:
  containers:
  - name: python-babitha
    image: babithadocker/babitha-first-repo
    ports:
    - name: python-port
      containerPort: 3000
