apiVersion: v1
kind: Pod
metadata:
  name: pod3
labels:
  app: helloworld
spec:
  containers:
  - name: python-babitha
    image: babithagit30/docker-demo-with-simple-python-app
    ports:
    - name:python-port
      containerPort: 8091
